config/routes.rb
DtimeRumble::Application.routes.draw do
  get "pages/home"
  match "/home" => "pages#home"

  get "dashboard" => "groups#index", as: "dashboard"

  resources :groups do
    member do
      post 'set_user'
    end
  end

  get "/login" => "sessions#login"

  get "/logout" => "sessions#logout"
  get "/check_email" => "sessions#check_email"
  get "/confirm" => "sessions#confirm", as: "confirming"
  get "/waiting" => "sessions#waiting", as: "waiting"
  post "/login" => "sessions#register"

  root :to => 'pages#home'

end

app/models/group.rb
require 'securerandom'
class Group < ActiveRecord::Base
  attr_accessible :title, :user_id, :slot_size, :start_date, :days
  before_create :assign_stuff
  validates_uniqueness_of :slug
  validates :slot_size, :numericality => {only_integer: true, greater_than_or_equal_to: 5, less_than_or_equal_to: 120}
  validates :days, :numericality => {only_integer: true, greater_than_or_equal_to: 5, less_than_or_equal_to: 14}
  belongs_to :user
  has_many :group_participants
  has_many :users, through: :group_participants


  def assign_stuff
    self.start_date = Time.now.to_date if self.start_date.blank?
    self.slot_size = 15 if self.slot_size.blank?
    self.days = 7 if self.days.blank?
    self.slug = SecureRandom.urlsafe_base64(12)
  end

  def min_duration
    # TODO make group attribute... if slot_size is 15 and they are only interesteed in minimum 1 hour intersections, this would be 4
    4
  end

  def valid_group_participants
    self.group_participants.select{|u| u.user && u.user.ready? }
  end
  def to_param
    slug
  end
  def owned_by?(user)
    return false unless user
    return false unless user.id
    user.id == user_id
  end
  def ready?
    !(title.blank? || user_id.blank?)
  end

  def fill_timecard_with(params)
    timecard.fill_with(params)
    self.serialized_timecard = timecard.serialize
  end
  def timecard
    return @timecard if @timecard
    @timecard = Timecard.new(start: self.start_date, slot_size: self.slot_size, days: self.days)
    @timecard.deserialize(serialized_timecard) if self.serialized_timecard
    @timecard
  end

  def timecard=(card)
    self.serialized_timecard = card.serialize
    @timecard = card
  end

  def best_timeslots
    results = []

    group_participants.size.downto(2) do |n|
      group_participants.combination(n).to_a.each do |subgroup|
        intersection = subgroup.inject(timecard.serialize.to_i(2)) do |x, participant|
          x &= participant.timecard.serialize.to_i(2)
        end.to_s(2)

        intersection.gsub!(/(?:^|0)(1{1,#{min_duration-1}})(?:0|$)/, "0" * '\1'.length)
        intersection = intersection.rjust(timecard.days * timecard.slots_per_day, "0") if intersection

        if intersection =~ /1{#{min_duration}}/
          results << timecard.clone_blank.deserialize(intersection)
        end
      end

      break if results.present?
    end

    results
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authorize_user!, only: [:index, :destroy]
  before_filter :finding_group, except: [:index, :create, :new]
  def index
    @group_list = current_user.groups
    @own_group_list = current_user.own_groups
    @group_list.select!{|g| g.ready? && !g.owned_by?(current_user)  }
    @own_group_list.select!{|g| g.ready?  }
  end

  def new
  end
  def show
    @group_timecard = build_group_timecard
    if logged_in?
      unless @me = current_user.responses.detect{|r| r.group_id == @group.id}
        @me = GroupParticipant.new(group_id: @group.id)
      end
      @timecard = @me.timecard
    else
      @timecard = Timecard.new
    end
  end

  def build_group_timecard
    return @group.timecard.clone_blank unless @group.valid?
    cards = @group.valid_group_participants
    cards = cards.reject{|u| u.user_id == current_user.id} if logged_in?
    cards_list = cards.each_with_object({}){|c, hash| hash[c.user] = c.timecard }
    @group.timecard.build_group_card(cards_list)
  end

  def edit
    @group_timecard = @group.timecard
    if logged_in?
      if current_user.id != @group.user_id
        redirect_to group_path(@group)
      else
      end
    else
    end
  end

  def set_user
    if logged_in?
      unless @me = current_user.responses.detect{|r| r.group_id == @group.id}
        @me = GroupParticipant.new(group_id: @group.id)
      end
      @me.fill_timecard_with(params[:slots])
      current_user.responses << @me
      @group.group_participants << @me
      current_user.save
      @group.save
      @me.save
      redirect_to group_path(@group), notice: "Saved Changes"
    else
      @me = GroupParticipant.new(group_id: @group.id)
      @me.fill_timecard_with(params[:slots])
      @group.group_participants << @me
      @group.save
      @me.save
      session[:participant_waiting] = @me.id
      redirect_to login_path
    end
  end

  def create
    if logged_in?
      params[:group]["user_id"] = current_user.id
      g = Group.create(params[:group])
    else
      g = Group.create(params[:group])
      session[:group_waiting] = g.id
    end
    if g.valid?
      redirect_to edit_group_path(g)
    else
      redirect_to dashboard_path, error: "Couldn't create the group for some reason"
    end
  end

  def destroy
    if current_user.id == @group.user_id && @group.destroy
      redirect_to dashboard_path, notice: "Removed"
    else
      redirect_to dashboard_path, error: "Couldn't delete the group (you probably didn't create it)"
    end
  end

  def update
    if logged_in?
      if current_user.id != @group.user_id
        redirect_to group_path(@group)
      else
        @group.update_attributes(params[:group])
        @group.fill_timecard_with(params[:slots])
        @group.group_participants.each do |p|
          p.mask_timecard_with(@group.timecard)
          p.save
        end
        @group.save
        redirect_to group_path(@group), notice: "Saved Changes"
      end
    else
      if @group.user_id.nil?
        @group.update_attributes(params[:group])
        @group.fill_timecard_with(params[:slots])
        @group.save
        redirect_to login_path
      else
        redirect_to group_path(@group)
      end
    end
  end

  def finding_group
    @group = Group.find_by_slug(params[:id])

    unless @group
      redirect_to dashboard_path, error: "Couldn't find that."
    end

  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_facepile.html.slim
- limit = 9
- if group_slot.respond_to?(:each)
  - group_slot.take(limit).each do |g|
    img(src=g.gravatar(20) alt=g.name)
  - if (size = (group_slot.length - limit)) > 0
    span +#{size} #{(size > 1 ? "others" : "other")}

app/views/groups/_form.html.slim
= form_for(Group.new) do |f|
  label
    ' Event Being Planned
    br
    = f.text_field :title, placeholder: "ex: Adam's Weclome BBQ"
  label
    ' Week Of
    br
    = f.text_field :start_date, value: Date.today + 7, class: "date_picker"
  label.slot_size
    ' How specific?
    br
    = f.select :slot_size, [ ["15 minute blocks", 15], ["30 minute blocks", 30], ["60 minute blocks", 60]]
  / label
    / ' Range
    / br
    / = f.select :days, [["7 days", 7], ["14 days", 14]]

  .form-actions
    =submit_tag("Submit", class: 'btn btn-primary')

app/views/groups/_timecard.html.slim
.calendar
  - 2.times do |x|
    .table_wrapper(class="#{x > 0 ? "show_body" : "show_head"}")
      table
        thead
          tr
            th
            - timecard.each_day do |day|
              th= day.date.strftime("%b %d<br > %A").html_safe
        tbody(class="#{masking_timecard ? "masked" : ''}")
          - group_slices = @group_timecard.slices
          - timecard.each_slice.zip(group_slices) do |slice, group_slice|
            tr(data-slot="#{slice.slot_offset}")
              th
                strong= slice.date.strftime("%I:%M %p")
              - slice.each_slot.zip(group_slice.slots).each_with_index do |(slot, group_slot), i|
                - day = (slice.date.to_date + i)
                - valid = (!masking_timecard || masking_timecard.fetch(i, slice.slot_offset))
                - valid = false if x == 0
                - highlighted = slot
                / Other users have chosen
                - grouped = group_slot.is_a?(Array)
                td(class="day_#{day.wday} #{grouped ? "grouped" : ""} #{valid ? "valid": ""} #{highlighted ? "highlighted" : ""}")
                  - unless x == 0
                    input(type="hidden" name="slots[#{i}][#{slice.slot_offset}]" value="false")
                    - if valid
                      = render partial: 'facepile', locals: {group_slot: group_slot}
                      input.check(type="checkbox" name="slots[#{i}][#{slice.slot_offset}]" value="true" checked=highlighted)

app/views/groups/edit.html.slim
.edit-group
  = form_for(@group, class: 'group cal') do |f|
    a.edit.btn.btn-link(href=group_path(@group)) Cancel
    label.name-change
      ' Change Event Name:
      = f.text_field :title, placeholder: "ex: Adam's Weclome BBQ"
    h1= (@group.title.blank? ? "New Group" : @group.title)
    .form-actions
      p Select valid times for your event
      = submit_tag("Save", class: "btn btn-primary disabled")
    br
    = render partial: 'timecard', locals: {timecard: @group.timecard, masking_timecard: nil}

app/views/groups/index.html.slim
.dashboard
  .row
    h1 My groups
    p Please create, select, or remove groups. Go on, give it a try.
    br

    - @own_group_list.each do |g|
      .group
        a(href=group_path(g) class="btn btn-success btn-large span5")= g.title
        = button_to("Remove", group_path(g), method: :delete, class: "btn btn-link btn-large span2", confirm: "Are you sure you want to remove group #{g.title}?")
    - @group_list.each do |g|
      .group
        a(href=group_path(g) class="btn btn-success btn-large span5")= g.title

  .form-actions
    = link_to "Create New Event", new_group_path, class: 'btn btn-large btn-primary right'

app/views/groups/new.html.slim
.row
  = render partial: 'form'

app/views/groups/show.html.slim
.view-group
  a.edit.btn.btn-success(href="mailto:?subject=When+would+be+a+good+time+for+#{@group.title.gsub(" ", "+")}&body=Let+me+know+at+#{CGI.escape(group_url(@group))}") Share
  - if @group.owned_by?(current_user)
    a.edit.btn.btn-link(href=edit_group_path(@group)) Edit

  h1= @group.title
  - if @group.valid_group_participants.size > 0
    p
      ' Participants:
      = @group.valid_group_participants.map{|p| p.user.display_name }.join(", ")

  = form_tag(set_user_group_path(@group), method: 'post', class: 'user cal') do
    .form-actions
      p Choose the times you are available
      = submit_tag("Save", class: "btn btn-primary disabled")
    = render partial: 'timecard', locals: {masking_timecard: @group.timecard, timecard: @timecard}